app/urls.py
from django.conf.urls import url
from .views import (PostCreate,PostDelete,PostList,comment_to_post,CommentDelete,like,)
app_name = "app"
urlpatterns = [
    url(r'^create/$', PostCreate, name="create"),
    url(r'^delete/(?P<pk>\d+)/$', PostDelete, name="delete"),
    url(r'^comment/(?P<pk>\d+)/$', comment_to_post, name="comment"),
    url(r'^like/(?P<pk>\d+)/$', like, name="like"),
    url(r'^comment/delete/(?P<pk>\d+)/$', CommentDelete, name="comment_delete"),
    url(r'^$', PostList, name="list"),
]

app/templates/app/comm_delete.html
<!doctype html>
<title>Delete</title>

{% block app %}
<form action="{% url 'app:create' %}" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete the <b>Comment</b> {{ object }} </p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

app/templates/app/comment_create.html
{% extends "base.html" %}
{% block content %}
<!doctype html>
<title>Create</title>
<div style="text-align:center">
{% block app %}
<form  action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="POST">
</form>
{% endblock %}
</div>
{% endblock content %}

app/templates/app/create.html
{% extends "base.html" %}
{% block content %}
<!doctype html>
<title>Create</title>
<div style="text-align:center">
{% block app %}
<form  action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="POST">
</form>
{% endblock %}
</div>
{% endblock content %}

app/templates/app/delete.html
<!doctype html>
<title>Delete</title>

{% block app %}
<form action="{% url 'app:create' %}" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete the <b>POST</b> "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

app/templates/app/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<!doctype html>
<head>
  <meta charset="UTF-8">
  <title>Home</title>
</head>

{% block app %}
{% if user.is_authenticated %}
  <div style="text-align:right"><a  href="{% url 'app:create' %}"><button>POST</button></a></div>
<div style="text-align:center" >
  {% if app %}
    {% for i in app %}
      <hr>
      {% if i.post_pic %}
      <img src="{{ i.post_pic.url }}" style="max-height:250; height: expression(this.width > 250 ? 250: true); max-width:250px;width: expression(this.width > 250 ? 250: true);"/> <br>
      {% endif %}
      <i><b>Caption:</b> {{ i.caption }}</i><br>
      <i><b>User:</b> {{ i.user }}</i><br>
      <i><b>Date:</b> {{ i.date_created }}</i><br>
      <a href="{% url 'app:like' i.id %}"><button type="submit">Like</button>
      {% if i.user == request.user %}
        <a href="{% url 'app:delete' i.id %}"><button>Delete</button></a>
      {% endif %}
      <a href="{% url 'app:comment' i.id %}"><button>Comment</button></a>
      <input type="button" class="btn btn-link" data-target="#{{ i.id }}" >Likes {{ i.likes.count }} </input>
      <button type="submit" class="btn btn-link" data-toggle="collapse" data-target="#{{ i.id }}" >Comments {{ i.comments.count }}</button>
        <div id="{{ i.id }}" class="collapse">
          <div id="comment" class="container">
            {% for c in i.comments.all %}
                <hr>
                <i>User: {{ c.user }}</i>
                <p>TEXT: {{ c.comment }}</p>
                {% if c.user == user %}
                  <a href="{% url 'app:comment_delete' c.id %}">Delete</a>
                {% endif %}
                <hr>
            {% endfor %}
          </div>
        </div>
      <hr>
    {% endfor %}
  {% else %}
    <b>NO POSTS!</b>
  {% endif %}
{% else %}
  <a href="/login/">Login to continue</a>
{% endif %}
</div>
{% endblock %}
{% endblock content %}

app/templates/app/not_allowed.html
<!doctype html>
<title>Delete</title>

{% block forum %}
<p>{{ txt }}</p>
<a href="{% url 'app:list' %}">Go Back</a>
{% endblock %}

app/templates/app/userprofile.html
{% extends "base.html" %}
{% block content %}
<div style="text-align:center">
  {% if user == request.user %}
    <div class="display-4">Hello, {{ user.username }}</div>
    <div style="text-align:right"><a  href="{% url 'app:create' %}"><button>POST</button></a></div>
    <div style=""><h4> Your Posts </h4></div>
  {% else %}
    <div class="display-4">Welcome to {{ user.username }}'s profile</div> <br>
    <div style="text-align:center"><a  href="{% url 'follow' user.id %}"><button>Follow</button></a></div><br>
  {% endif %}

  {% if follow %}
    {% for i in follow %}
      {% if i.user == user %}
        <b>{{ i.followers.all }}</b><br>
      {% endif %}
    {% endfor %}
  {% endif %}

  {% if post %}
  {% for i in post %}
  <hr>
  {% if i.post_pic %}
  <img src="{{ i.post_pic.url }}" style="max-height:250; height: expression(this.width > 250 ? 250: true); max-width:250px;width: expression(this.width > 250 ? 250: true);"/> <br>
  {% endif %}
  <i><b>Caption:</b> {{ i.caption }}</i><br>
  <i><b>User:</b> {{ i.user }}</i><br>
  <i><b>Date:</b> {{ i.date_created }}</i><br>
  <a href="{% url 'app:like' i.id %}"><button type="submit">Like</button>
  {% if i.user == request.user %}
    <a href="{% url 'app:delete' i.id %}"><button>Delete</button></a>
  {% endif %}
  <a href="{% url 'app:comment' i.id %}"><button>Comment</button></a>
  <input type="button" class="btn btn-link" data-target="#{{ i.id }}" >Likes {{ i.likes.count }} </input>
  <button type="submit" class="btn btn-link" data-toggle="collapse" data-target="#{{ i.id }}" >Comments {{ i.comments.count }}</button>
    <div id="{{ i.id }}" class="collapse">
      <div id="comment" class="container">
        {% for c in i.comments.all %}
            <hr>
            <i>User: {{ c.user }}</i>
            <p>TEXT: {{ c.comment }}</p>
            {% if c.user == request.user %}
              <a href="{% url 'app:comment_delete' c.id %}">Delete</a>
            {% endif %}
            <hr>
        {% endfor %}
      </div>
    </div>
  <hr>
  {% endfor %}
  {% else %}
    <b>No Post's Yet</b>
  {% endif %}
</div>
{% endblock content %}
















<!-- <!DOCTYPE html>
<html>
<body>

<p id="demo">Click the button to get your position.</p>

<button onclick="getLocation()">Try It</button>

<div id="mapholder"></div>

<script src="https://maps.google.com/maps/api/js?key=AIzaSyBhKtVh3PLexqEmFhbb5iFB6hoe10zSBpw"></script>

To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
<script> 
 var x = document.getElementById("demo");
 function getLocation() {
     if (navigator.geolocation) {
         navigator.geolocation.getCurrentPosition(showPosition, showError);
     } else {
         x.innerHTML = "Geolocation is not supported by this browser.";
     }
 }

function showPosition(position) {
    var lat = position.coords.latitude;
    var lon = position.coords.longitude;
    var latlon = new google.maps.LatLng(lat, lon)
    var mapholder = document.getElementById('mapholder')
    mapholder.style.height = '250px';
    mapholder.style.width = '500px';

    var myOptions = {
    center:latlon,zoom:14,
    mapTypeId:google.maps.MapTypeId.ROADMAP,
    mapTypeControl:false,
    navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}
    }

    var map = new google.maps.Map(document.getElementById("mapholder"), myOptions);
    var marker = new google.maps.Marker({position:latlon,map:map,title:"You are here!"});
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}
</script>

</body>
</html>
 -->

app/templates/app/users.html
{% extends "base.html" %}
{% block content %}
  {% for i in all_users %}
    {% if i.is_active %}
        <li><a href="{% url 'userprofile' i.id %}">{{ i }}</a></li> <br>
    {% endif %}
  {% endfor %}
{% endblock content %}